name: Deploy Project to Azure VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.MY_SSH_PRIVATE_KEY_FOR_VM }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 20.92.55.101 >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          scp -i ~/.ssh/id_rsa -r ./dist/* azureuser@20.92.55.101:/home/azureuser/node-app

      - name: Restart app on VM
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.92.55.101 "cd /home/azureuser/node-app && npm install && pm2 restart app"
