name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:20

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Get SSH KEYS AND PERMISSIONS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_SSH_PRIVATE_KEY_FOR_VM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa


      - name: Deploy Next.js app to Azure VM
        run: |
          rsync -avz --exclude node_modules --exclude .git -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ azureuser@20.121.68.255:/home/azureuser/node-app

      - name: Restart app on VM
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.121.68.255 "cd /home/azureuser/node-app && npm install --production && pm2 restart app"